version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: "/apps/callisto"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: gomod
    directory: "/packages/juno"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
