version: "3.6"
services:
    hasura:
        image: hasura/graphql-engine:v2.6.1.cli-migrations-v3${HASURA_IMAGE_SUFFIX:-}
        restart: always
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://user:password@database:5432/database
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            HASURA_GRAPHQL_DEV_MODE: "true"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ACTION_BASE_URL: http://host.docker.internal:3000
        volumes:
            - ./hasura/metadata:/hasura-metadata
        ports:
            - "8080:8080"

    database:
        image: postgres:17
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database
        volumes:
            - ./database/schema:/docker-entrypoint-initdb.d
