name: "Build explorer image"

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
      target:
        required: true
        type: string
      tag:
        required: true
        type: string
      environment:
        required: true
        type: string
        description: "Deployment environment (mainnet, testnet, devnet)"

permissions:
  # Needed to configure aws credentials step
  id-token: write
  contents: read
  # Needed to push images to GitHub Container Registry
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: ${{ inputs.environment }}

    steps:
      - name: Shorten TAG in case of SHA
        id: env-vars
        shell: bash
        env:
          FULL_SHA: ${{ inputs.tag }}
        run: echo "TAG=${FULL_SHA::16}" >> $GITHUB_OUTPUT

      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub 👤
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Write explorer env file
        run: echo "$EXPLORER_ENV" > /tmp/explorer.env
        env:
          EXPLORER_ENV: ${{ secrets.EXPLORER_ENV }}

      # Build docker image
      - name: Build docker image
        uses: docker/build-push-action@v5
        env:
          TAG: ${{ steps.env-vars.outputs.TAG }}
        with:
          context: .
          file: docker/explorer.Dockerfile
          provenance: false
          target: ${{ inputs.target }}
          push: ${{ inputs.push }}
          tags: |
            ghcr.io/xrplevm/cosmos-explorer/explorer-${{ inputs.environment }}:${{ env.TAG }}
          outputs: type=image
          build-args: |
            BASE_IMAGE=ghcr.io/xrplevm/cosmos-explorer/base:${{ env.TAG }}
            TURBO_TEAM=peersyst
          secret-files: |
            explorer_env=/tmp/explorer.env
          secrets: |
            turbo_token=${{ secrets.TURBO_TOKEN }}
