name: "Build and deploy"

on:
  push:
    branches:
      - main

jobs:
  build-base:
    uses: ./.github/workflows/build-base.yaml
    secrets: inherit
    with:
      push: true
      tag: ${{ github.sha }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-base
      cancel-in-progress: true

  build-callisto:
    needs: [ build-base ]
    uses: ./.github/workflows/build-callisto.yaml
    secrets: inherit
    with:
      push: true
      target: release
      tag: ${{ github.sha }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build-callisto
      cancel-in-progress: true
